version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bento_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bento_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bento_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bento_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bento_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bento_network
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  bento_network:
    driver: bridge

volumes:
  postgres_data:
