version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bento_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bento_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app:cached
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bento_db
      PYTHONUNBUFFERED: 1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bento_network
    command: sleep infinity

networks:
  bento_network:
    driver: bridge

volumes:
  postgres_data: